version: '3'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 10

  scraper:
    container_name: scrape_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db:
    driver: local
